//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int Appointment_id { get; set; }
        public int id_doctor { get; set; }
        public int id_patient { get; set; }
        public string Info_about_appointment { get; set; }
        public int id_diagnosis { get; set; }
        public string Theraphy { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual list_of_diagnoses list_of_diagnoses { get; set; }
        public virtual patient patient { get; set; }
    }
}
