//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public appointment()
        {
            this.patient_medical_history = new HashSet<patient_medical_history>();
        }
    
        public int Appointment_id { get; set; }
        public int id_doctor { get; set; }
        public int id_patient { get; set; }
        public string Info_about_appointment { get; set; }
        public int id_diagnosis { get; set; }
        public string Theraphy { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual list_of_diagnoses list_of_diagnoses { get; set; }
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_medical_history> patient_medical_history { get; set; }
    }
}
