//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicCourseProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class doctors_timetable
    {
        public int Timetable_id { get; set; }
        public int id_doctor { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }

        [NotMapped]
        public List<doctor> ListDoctor { get; set; }
        [NotMapped]
        public string FIO { get; set; }
        [NotMapped]
        public string Specialty { get; set; }

        public virtual doctor doctor { get; set; }
    }
}
