//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicCourseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicEntities : DbContext
    {
        public PolyclinicEntities()
            : base("name=PolyclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<appointment> appointment { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<doctors_timetable> doctors_timetable { get; set; }
        public virtual DbSet<list_of_diagnoses> list_of_diagnoses { get; set; }
        public virtual DbSet<list_of_specialty> list_of_specialty { get; set; }
        public virtual DbSet<making_appointment> making_appointment { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<prescription> prescription { get; set; }
    }
}
